# Generated by Django 4.2.1 on 2023-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
